server:
    port: 3000
spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group_id
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    redis:
        host: localhost
        port: 6379
    application:
        name: user-service
    datasource:
        username: ${USER_DB:postgres}
        password: ${PASSWORD_DB:postgres}
        url: ${HOST_DB:jdbc:postgresql://localhost:3306/hunt}
        driver-class-name: ${DRIVER_DB:org.postgresql.Driver}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
            show-sql: true
